export const data=[
   {
      title:'بيليل',
      dice:'dgdfg',
      revue:4,
      img:require('./images/1.jfif'),
   },
   {
      title:'بيليل',
      dice:'dgdfg',
      revue:4,
      img:require('./images/2.jpg'),
   },
   {
      title:'بيليل',
      dice:'dgdfg',
      revue:4,
      img:require('./images/3.jfif'),
   },
   {
      title:'بيليل',
      dice:'dgdfg',
      revue:4,
      img:require('./images/4.jpg'),
   },
]